apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx
  labels:
    project: roboshop
    component: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: project
            operator: In
            values:
            - roboshop   
  containers: 
  - name: nginx 
    image: nginx